steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - send_email_alert
      - --runtime=python310
      - --region=europe-west1
      - --entry-point=send_email_alert
      - --trigger-topic=projects/analystack/subscriptions/DataMaintenance_test2-sub
      - --source=alert-click-ga4/  # Specifica la sottocartella